# Build settings
env: "production"
permalink: "none" 
exclude: ["LICENSE"]

# Theme configuration
theme: "siimple-theme"
color: "blue"

# Sass build settings
sass:
    style: "compressed"
    load_paths: ["../bower_components", "_sass"]

# Site settings
title: "siimple"
version: "3.1.1"
url: "https://docs.siimple.xyz"

# Documentation settings
documentation:
    issues: "https://github.com/siimple/siimple/issues"

# Navbar settings
navbar:
    - title: "Go to siimple.xyz"
      url: "https://www.siimple.xyz"

# Footer settings
footer:
    contributors: "https://github.com/siimple/siimple/graphs/contributors"
    privacy_url: "https://www.siimple.xyz/legal/privacy.html"
    cookies_url: "https://www.siimple.xyz/legal/cookies.html"
    code_license: 
        title: "MIT License"
        url: "https://github.com/siimple/siimple/blob/develop/LICENSE"
    docs_license: 
        title: "Creative Commons CC BY 4.0 License"
        url: "https://github.com/siimple/siimple/blob/develop/docs/LICENSE"
    social:
        - title: "GitHub"
          url: "https://github.com/siimple/siimple"
        - title: "Twitter"
          url: "https://twitter.com/siimplecss"
        - title: "Gitter"
          url: "https://gitter.im/siimple/siimple"

## Search settings
search:
    entry: "/search.html"
    database: "./assets/search.json"
    title: "Search"
    subtitle: "Search in <strong>siimple</strong> docs"

# Cookies settings
cookies:
    analytics: "UA-70800807-5"
    path: "/"
    domain: ".siimple.xyz"

